services:
  - type: web
    name: tic-tac-toe-ws
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn render_server:app --host 0.0.0.0 --port $PORT
